name: "Github Profile 3D Contributions"

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Generate 3D contributions"
    steps:

      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1

      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.CONTRIBUTION }}
          USERNAME: ${{ github.repository_owner }}
      - name: "Commit and push"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "generated"; then
            git push
          fi